apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 {{- if .Values.sename}}
 name: ingress-router-{{ .Values.sename }}
 {{- else }}
 name: ingress-router
 {{- end }}
 annotations:
   kubernetes.io/ingress.class: nginx
   kubernetes.io/ingress.global-static-ip-name: "bootcamp-static-ip"
spec:
  rules:
  {{- if .Values.sename}}
  - host: {{ .Values.sename }}.cie-bootcamp.co.uk
  {{- else }}
  - host: cie-bootcamp.co.uk
  {{- end }}
    http:
     paths:
     - backend:
       {{- if .Values.sename}}
          serviceName: payment-service-{{ .Values.sename }}-svc
       {{- else }}
          serviceName: payment-service-svc
       {{- end }}
          servicePort: 8080
